package main

import "strings"

func getMaintenanceTexts(lang string) map[string]string {
	lang = strings.ToLower(lang)
	if strings.HasPrefix(lang, "ko") {
		return map[string]string{
			"Title":                  "유지보수 설정",
			"NavbarBrand":            "미디어 서버",
			"NavbarDashboard":        "대시보드",
			"PageHeader":             "유지보수 설정",
			"BreadcrumbHome":         "홈",
			"BreadcrumbSettings":     "설정",
			"SuccessSaved":           "설정을 저장했습니다.",
			"SuccessSavedRestart":    "설정을 저장했습니다. 모든 녹화를 새 저장소에서 재시작합니다.",
			"CardRetention":          "보관 정책",
			"LabelRetentionDays":     "보관 기간 (일)",
			"HelpRetentionDays":      "녹화 데이터를 유지할 일수입니다. 초과분은 날짜별 폴더를 삭제합니다.",
			"LabelRetentionCapacity": "보관 용량 (GB)",
			"HelpRetentionCapacity":  "저장 용량이 이 값을 초과하면 가장 오래된 날짜 폴더부터 삭제합니다.",
			"LabelBaseRoot":          "기본 보관 경로",
			"HelpBaseRoot":           "녹화 데이터가 저장될 최상위 디렉터리입니다. 탐색 버튼을 사용하거나 직접 경로를 입력하세요.",
			"ButtonBrowse":           "찾아보기",
			"LabelSafetyFreeSpace":   "최소 여유 공간 (GB)",
			"HelpSafetyFreeSpace":    "디스크 여유 공간이 이 값보다 작아지면 가장 오래된 녹화 폴더를 추가로 삭제합니다.",
			"ButtonSave":             "저장",
			"ModalTitle":             "폴더 선택",
			"ModalPlaceholder":       "경로를 직접 입력하거나 목록에서 선택하세요.",
			"ModalGo":                "이동",
			"ModalCancel":            "취소",
			"ModalSelect":            "선택",
			"Loading":                "로딩 중...",
			"UpOneLevel":             "상위 폴더로 이동",
			"NoSubfolders":           "하위 폴더가 없습니다.",
			"ErrorPrefix":            "오류: ",
			"ErrorBaseRootRequired":  "보관 경로를 비울 수 없습니다.",
			"ErrorBaseRootInvalid":   "존재하지 않거나 사용할 수 없는 경로입니다.",
		}
	}

	if strings.HasPrefix(lang, "ja") {
		return map[string]string{
			"Title":                  "メンテナンス設定",
			"NavbarBrand":            "メディアサーバー",
			"NavbarDashboard":        "ダッシュボード",
			"PageHeader":             "メンテナンス設定",
			"BreadcrumbHome":         "ホーム",
			"BreadcrumbSettings":     "設定",
			"SuccessSaved":           "設定が保存されました。",
			"SuccessSavedRestart":    "設定を保存しました。すべての録画を新しい保存先で再起動します。",
			"CardRetention":          "保持ポリシー",
			"LabelRetentionDays":     "保持日数",
			"HelpRetentionDays":      "録画データを保持する日数です。上限を超えると古い日付のフォルダーが削除されます。",
			"LabelRetentionCapacity": "保持容量 (GB)",
			"HelpRetentionCapacity":  "保存容量がこの値を超えると、最も古い日付のフォルダーから削除します。",
			"LabelBaseRoot":          "保存ルート",
			"HelpBaseRoot":           "録画データを保存するルートディレクトリです。「参照」ボタンで探索するかパスを入力してください。",
			"ButtonBrowse":           "参照",
			"LabelSafetyFreeSpace":   "安全空き容量 (GB)",
			"HelpSafetyFreeSpace":    "空き容量がこの値を下回ると、最も古い録画フォルダーが削除されます。",
			"ButtonSave":             "変更を保存",
			"ModalTitle":             "フォルダーを選択",
			"ModalPlaceholder":       "パスを入力するか一覧から選択してください。",
			"ModalGo":                "移動",
			"ModalCancel":            "キャンセル",
			"ModalSelect":            "選択",
			"Loading":                "読み込み中...",
			"UpOneLevel":             "上のフォルダーへ",
			"NoSubfolders":           "サブフォルダーがありません。",
			"ErrorPrefix":            "エラー: ",
			"ErrorBaseRootRequired":  "保存先は空にできません。",
			"ErrorBaseRootInvalid":   "存在しない、または利用できないパスです。",
		}
	}

	if strings.HasPrefix(lang, "vi") {
		return map[string]string{
			"Title":                  "Cài đặt bảo trì",
			"NavbarBrand":            "Máy chủ Media",
			"NavbarDashboard":        "Bảng điều khiển",
			"PageHeader":             "Cài đặt bảo trì",
			"BreadcrumbHome":         "Trang chủ",
			"BreadcrumbSettings":     "Cài đặt",
			"SuccessSaved":           "Đã lưu cài đặt thành công.",
			"SuccessSavedRestart":    "Đã lưu cài đặt. Đang khởi động lại mọi bản ghi trong thư mục lưu trữ mới.",
			"CardRetention":          "Chính sách lưu trữ",
			"LabelRetentionDays":     "Số ngày lưu trữ",
			"HelpRetentionDays":      "Số ngày giữ lại dữ liệu đã ghi. Khi vượt quá giới hạn, các thư mục ngày cũ hơn sẽ bị xóa.",
			"LabelRetentionCapacity": "Dung lượng lưu trữ (GB)",
			"HelpRetentionCapacity":  "Khi dung lượng vượt giá trị này, các thư mục ngày cũ nhất sẽ bị xóa trước.",
			"LabelBaseRoot":          "Thư mục gốc lưu trữ",
			"HelpBaseRoot":           "Thư mục gốc lưu trữ bản ghi. Dùng nút Duyệt hoặc nhập đường dẫn thủ công.",
			"ButtonBrowse":           "Duyệt",
			"LabelSafetyFreeSpace":   "Dung lượng trống an toàn (GB)",
			"HelpSafetyFreeSpace":    "Nếu dung lượng trống thấp hơn giá trị này, hệ thống sẽ xóa thư mục ghi hình cũ nhất.",
			"ButtonSave":             "Lưu thay đổi",
			"ModalTitle":             "Chọn thư mục",
			"ModalPlaceholder":       "Nhập đường dẫn hoặc chọn từ danh sách.",
			"ModalGo":                "Đi",
			"ModalCancel":            "Hủy",
			"ModalSelect":            "Chọn",
			"Loading":                "Đang tải...",
			"UpOneLevel":             "Lên một thư mục",
			"NoSubfolders":           "Không có thư mục con.",
			"ErrorPrefix":            "Lỗi: ",
			"ErrorBaseRootRequired":  "Thư mục gốc lưu trữ không được để trống.",
			"ErrorBaseRootInvalid":   "Đường dẫn không tồn tại hoặc không thể sử dụng.",
		}
	}

	if strings.HasPrefix(lang, "zh-tw") || (strings.HasPrefix(lang, "zh") && strings.Contains(lang, "tw")) {
		return map[string]string{
			"Title":                  "維護設定",
			"NavbarBrand":            "媒體伺服器",
			"NavbarDashboard":        "控制台",
			"PageHeader":             "維護設定",
			"BreadcrumbHome":         "首頁",
			"BreadcrumbSettings":     "設定",
			"SuccessSaved":           "設定已成功儲存。",
			"SuccessSavedRestart":    "設定已儲存。正在於新的儲存路徑重新啟動所有錄影。",
			"CardRetention":          "保留政策",
			"LabelRetentionDays":     "保留天數",
			"HelpRetentionDays":      "錄影資料的保留天數。超過上限時會刪除較舊的日期資料夾。",
			"LabelRetentionCapacity": "保留容量 (GB)",
			"HelpRetentionCapacity":  "當儲存容量超過此值時，會優先刪除最舊的日期資料夾。",
			"LabelBaseRoot":          "儲存根目錄",
			"HelpBaseRoot":           "錄影檔案的根目錄。請使用「瀏覽」按鈕或直接輸入路徑。",
			"ButtonBrowse":           "瀏覽",
			"LabelSafetyFreeSpace":   "安全剩餘空間 (GB)",
			"HelpSafetyFreeSpace":    "若磁碟剩餘空間低於此值，系統將刪除最舊的錄影資料夾。",
			"ButtonSave":             "儲存變更",
			"ModalTitle":             "選擇資料夾",
			"ModalPlaceholder":       "請輸入路徑或從列表中選擇。",
			"ModalGo":                "前往",
			"ModalCancel":            "取消",
			"ModalSelect":            "選取",
			"Loading":                "載入中...",
			"UpOneLevel":             "返回上一層",
			"NoSubfolders":           "沒有子資料夾。",
			"ErrorPrefix":            "錯誤: ",
			"ErrorBaseRootRequired":  "儲存根目錄不得為空。",
			"ErrorBaseRootInvalid":   "此路徑不存在或不可使用。",
		}
	}

	if strings.HasPrefix(lang, "ru") {
		return map[string]string{
			"Title":                  "Настройки обслуживания",
			"NavbarBrand":            "Медиа-сервер",
			"NavbarDashboard":        "Панель управления",
			"PageHeader":             "Настройки обслуживания",
			"BreadcrumbHome":         "Главная",
			"BreadcrumbSettings":     "Настройки",
			"SuccessSaved":           "Настройки успешно сохранены.",
			"SuccessSavedRestart":    "Настройки сохранены. Все записи будут перезапущены в новом хранилище.",
			"CardRetention":          "Политика хранения",
			"LabelRetentionDays":     "Дни хранения",
			"HelpRetentionDays":      "Количество дней хранения записей. После превышения лимита старые папки удаляются.",
			"LabelRetentionCapacity": "Объём хранения (ГБ)",
			"HelpRetentionCapacity":  "Когда объём данных превышает это значение, сначала удаляются самые старые папки.",
			"LabelBaseRoot":          "Корневая папка хранения",
			"HelpBaseRoot":           "Корневая директория для записей. Используйте «Обзор» или укажите путь вручную.",
			"ButtonBrowse":           "Обзор",
			"LabelSafetyFreeSpace":   "Минимальный свободный объём (ГБ)",
			"HelpSafetyFreeSpace":    "Если свободное место меньше этого значения, удаляются самые старые папки записей.",
			"ButtonSave":             "Сохранить",
			"ModalTitle":             "Выбор папки",
			"ModalPlaceholder":       "Введите путь или выберите из списка.",
			"ModalGo":                "Перейти",
			"ModalCancel":            "Отмена",
			"ModalSelect":            "Выбрать",
			"Loading":                "Загрузка...",
			"UpOneLevel":             "На уровень вверх",
			"NoSubfolders":           "Нет подпапок.",
			"ErrorPrefix":            "Ошибка: ",
			"ErrorBaseRootRequired":  "Корневой каталог хранения не может быть пустым.",
			"ErrorBaseRootInvalid":   "Путь не существует или недоступен.",
		}
	}

	return map[string]string{
		"Title":                  "Maintenance Settings",
		"NavbarBrand":            "Media Server",
		"NavbarDashboard":        "Dashboard",
		"PageHeader":             "Maintenance Settings",
		"BreadcrumbHome":         "Home",
		"BreadcrumbSettings":     "Settings",
		"SuccessSaved":           "Settings saved successfully.",
		"SuccessSavedRestart":    "Settings saved. Restarting all recordings in the new storage location.",
		"CardRetention":          "Retention Policy",
		"LabelRetentionDays":     "Retention Days",
		"HelpRetentionDays":      "Number of days to keep recorded footage. Older day folders will be deleted when exceeding the limit.",
		"LabelRetentionCapacity": "Retention Capacity (GB)",
		"HelpRetentionCapacity":  "When stored size exceeds this capacity, the oldest day folders are removed first.",
		"LabelBaseRoot":          "Base Root",
		"HelpBaseRoot":           "Top-level directory for recordings. Use Browse to explore the server or enter a path manually.",
		"ButtonBrowse":           "Browse",
		"LabelSafetyFreeSpace":   "Default Safety Free Space (GB)",
		"HelpSafetyFreeSpace":    "If free disk space drops below this value, the system deletes the oldest recording folders.",
		"ButtonSave":             "Save changes",
		"ModalTitle":             "Select Folder",
		"ModalPlaceholder":       "Type a path or choose from the list.",
		"ModalGo":                "Go",
		"ModalCancel":            "Cancel",
		"ModalSelect":            "Select",
		"Loading":                "Loading...",
		"UpOneLevel":             "Up one level",
		"NoSubfolders":           "No subfolders.",
		"ErrorPrefix":            "Error: ",
		"ErrorBaseRootRequired":  "Base root cannot be empty.",
		"ErrorBaseRootInvalid":   "Path does not exist or is not accessible.",
	}
}
